Adicinando conteúdo sobre codeanywhere
railsgirlsportoalegre/tutorial pull request #1
Opened 2017-10-26 17:32 UTC by carolmoers

**Qual é o propósito deste Pull Request?**
A ideia desse PR é adicionar o conteúdo sobre codeanywhere para que durante o tutorial as meninas consigam ter um guia de como criar a conta e o container. 

**O que foi feito para alcançar esse propósito?**
Adicionei a sessão em codeanywhere com:
* Codeanywhere
* O que é o Codeanywhere?
* Criando uma conta]
* Criando um container

2017-10-26 23:34 UTC, theendie requested changes

2017-10-26 23:34 UTC, asserdna commented on codeanywhere/criando_container.md
> +Para que tudo dê certinho, vamos nos certificar de escolher aquela que diz "Ruby" **e** "Ubuntu 14.04".
Acho que as meninas se sentiriam mais seguras se tivessem uma imagem aqui dessa janela com essa opção, apenas para validar se elas estão fazendo certo. Seria massa colocarmos. 😄

2017-10-26 23:34 UTC, asserdna commented on codeanywhere/o_que_e.md
> +O Codeanywhere nos oferece um computador como outro qualquer, para podermos desenvolver nosso código. O diferencial dele é, quando vai utilizá-lo, você já vai escolher o sistema operacional e alguns
> O diferencial dele é, quando vai utilizá-lo, você já vai escolher o sistema operacional e alguns recursos que já vem instalados (por exemplo, o próprio interpretador da linguagem Ruby).

Acho que seria massa colocar de uma maneira um pouco mais clara, algo como: 

> O diferencial dele é que quando escolhemos o nosso sistema operacional (Ubuntu 14.04), escolhemos também os recursos que queremos que venham instalados (por exemplo, o próprio interpretador da linguagem Ruby).

O que acha? 😃

2017-10-27 18:51 UTC, carolmoers commented on codeanywhere/o_que_e.md
> +O Codeanywhere nos oferece um computador como outro qualquer, para podermos desenvolver nosso código. O diferencial dele é, quando vai utilizá-lo, você já vai escolher o sistema operacional e alguns
massa, ajustei. muito bom 🦄

2017-10-27 18:51 UTC, carolmoers commented on codeanywhere/criando_container.md
> +Para que tudo dê certinho, vamos nos certificar de escolher aquela que diz "Ruby" **e** "Ubuntu 14.04".
siiim, eu tinha até a imagem, mas passei reto nisso, já adicionei :)

2017-10-28 20:45 UTC, theendie approved these changes

2017-10-28 20:45 UTC, merged