Adicionando linha de comando
railsgirlsportoalegre/tutorial pull request #3
Opened 2017-10-27 19:21 UTC by carolmoers

**Qual é o propósito deste Pull Request?**
A ideia desse PR é adicionar o conteúdo sobre linha de comando.

**O que foi feito para alcançar esse propósito?**
Adicionei a sessão em linha de comando com:

* Introdução a linha de comando
  * O que é a linha de comando?
  * Conhecendo a linha de comando
  * Seu primeiro comando (YAY!)
  * O básico
    * Pasta atual
    * Criando uma pasta
    * Listando arquivos e pastas
    * Entrando nas pastas
    * Exercite-se!
    * Limpando
    * Resumo

2017-11-01 14:25 UTC, theendie requested changes
Faltou só a imagem ssh.png :D O resto está lindo <3

2017-11-01 14:25 UTC, theendie commented on linha_de_comando/conhecendo.md
> +![SSH](../images/linha_de_comando/ssh.png)
A imagem não existe na pasta linha_de_comando. :P

2017-11-02 11:59 UTC, carolmoers commented on linha_de_comando/conhecendo.md
> +![SSH](../images/linha_de_comando/ssh.png)
ops :P

2017-11-02 14:55 UTC, theendie approved these changes

2017-11-02 21:58 UTC, merged